### ISSUE TITLE
Add application package to Yocto

### ISSUE THREAD

**Issue by atharvanan1** [atharvanan1/aesd_project_build#6]
Add applications from [Application Repository](https://github.com/atharvanan1/aesd_linux_app). Set them up as per hello-world recipe.

DoD: Applications are present in rootfs. They run as intended and pass the tests.

Blocker: #2 #3 (resolved)

**Comment by bcis93** [comment]
Azure has a [Yocto layer](https://github.com/Azure/meta-iotedge)! This should install the runtime environment needed for iotedge. I am working on adding this layer to a Yocto build to test it out.

**Comment by bcis93** [comment]
Moving into sprint 1 because it resolves https://github.com/atharvanan1/aesd_linux_app/issues/4

**Comment by atharvanan1** [comment]
Tested with a build for Azure Yocto Layers - needs validation

**Comment by atharvanan1** [comment]
Facing some issue with building the application. Possibly, there is an error in our makefile configuration, or the proprietary libraries have some error that needs to be patched.

**Comment by bcis93** [comment]
Currently blocked  - it looks like [meta-iot-cloud layer](https://github.com/intel-iot-devkit/meta-iot-cloud) might not be building the azure iot sdk quite right. The build of that layer succeeds, but when we try to build our app based on the libraries that got installed, there are some build errors (looks like include path errors)

**Comment by atharvanan1** [comment]
Developed a CMake based compilation solution to fix include path errors.

**Comment by atharvanan1** [comment]
Blocker: Compilation gives linker error, as certain libraries are not present

Libraries not present:
`prov_auth_client`
`hsm_security_client`
`parson`
`uhttp`

These libraries are not present in sysroot

**Comment by atharvanan1** [comment]
A solution seems to be adding individual recipes for building these libraries. Dan had tried using a patch to modify how the meta-iot-cloud recipes built everything, however it ran into an issue - [link](https://github.com/dwalkes/meta-iot-cloud/commit/a99f4144015bd92c1444dd0d93752375444024a1).

His suggestion was to build each libraries individually, so we will now try to integrate that into our solution

**Comment by atharvanan1** [comment]
Further progress was made.
Identified three methods to solve this problem: 
1. Using meta-iot-cloud with patches to install provisioning-client
2. Using custom recipes-azure
3. Installing individual libraries

**Comment by bcis93** [comment]
azure_app builds and is present in rootfs with 5517f162ee7d42902146bf4a508b04a05cdc88ec
